# Generated by Django 3.2.9 on 2022-03-05 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshopapp', '0010_auto_20220302_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cusrtomer',
            new_name='customer_id',
        ),
    ]
